#!/bin/bash
# TASK-0035E10 — SENMA wrapper around crazymax/fail2ban entrypoint.
#
# Copies repository-versioned filters/actions/jails into /data (writable
# fail2ban data volume), injects ignoreip from env, then execs stock
# /entrypoint.sh. Never mounts docker.sock. Never privileged.
set -euo pipefail

SRC="${SENMA_FAIL2BAN_SRC:-/senma-fail2ban-src}"
DATA="${FAIL2BAN_DATA:-/data}"

mkdir -p "$DATA/db" "$DATA/action.d" "$DATA/filter.d" "$DATA/jail.d"

copy_dir() {
    local kind="$1"
    local from="$SRC/$kind"
    local to="$DATA/$kind"
    [ -d "$from" ] || return 0
    # Replace managed files so upgrades pick up repo changes; leave
    # unrelated operator drops (if any) alone when names do not collide.
    find "$from" -maxdepth 1 -type f -print0 2>/dev/null \
        | while IFS= read -r -d '' f; do
            cp -f "$f" "$to/$(basename "$f")"
        done
}

copy_dir filter.d
copy_dir action.d
copy_dir jail.d

# Allowlist: loopback always; SENMA compose `mag` network ONLY
# (compose.yaml networks.mag.ipam.subnet = 172.28.0.0/16 — project-pinned,
# NOT a blanket RFC1918 allow). Plus explicit env lists (space/comma
# separated). Do NOT auto-allowlist 10/8, 172.16/12, or 192.168/16.
# Do NOT resolve untrusted DNS into ignoreip.
#
# In pilot/host mode, public SIP does not arrive from 172.28/16; the entry
# remains so bridge/dev compose-internal peers in Asterisk logs are never
# banned, and so the ignoreip contract stays identical across topologies.
IGNORE_DEFAULT="127.0.0.0/8 ::1 172.28.0.0/16"
IGNORE_EXTRA="${SENMA_SECURITY_IGNOREIP:-}"
IGNORE_PROVIDERS="${SENMA_SIP_PROVIDER_ALLOWLIST:-}"
IGNORE_COMBINED="$IGNORE_DEFAULT"
for chunk in $IGNORE_EXTRA $IGNORE_PROVIDERS; do
    chunk="${chunk//,/ }"
    for item in $chunk; do
        [ -n "$item" ] || continue
        IGNORE_COMBINED="$IGNORE_COMBINED $item"
    done
done

cat > "$DATA/jail.d/zz-senma-ignoreip.local" <<EOF
# Generated by senma-fail2ban-entrypoint.sh — do not edit in the container.
# Source: loopback defaults + SENMA_SECURITY_IGNOREIP + SENMA_SIP_PROVIDER_ALLOWLIST
[DEFAULT]
ignoreip = ${IGNORE_COMBINED}
EOF

echo "[senma-fail2ban] ignoreip=${IGNORE_COMBINED}"
echo "[senma-fail2ban] handing off to stock fail2ban entrypoint"

exec /entrypoint.sh "$@"
