#!/usr/bin/env python3
"""SENMA WSS platform test client (TASK-0028Z).

A minimal, standard-library-only SIP-over-WebSocket (RFC 7118) client:
real TLS handshake -> real WebSocket upgrade at a given path (default
/ws) with the "sip" subprotocol -> optionally, a real SIP REGISTER
transaction (including a digest-auth round trip) over that connection.

This exists because no available test client speaks this protocol:
baresip's Debian package has no SIP-over-WebSocket transport compiled in
at all. It intentionally does NOT validate the server's TLS certificate
(--mode register/handshake both use ssl.CERT_NONE) -- the certificate
used in this project's dev/test environment is a self-signed TEST-ONLY
fixture generated by docker/asterisk-entrypoint.sh (see
docs/tasks/0028z-wss-asterisk-http-enablement.md); real certificate
trust/validation is not this task's concern (see TASK-0029A).

Exit codes: 0 = the requested proof succeeded, 1 = the server responded
but the proof failed (bad handshake / non-2xx final SIP status), 2 =
usage error. An unhandled exception (connection refused, TLS failure,
timeout) prints a traceback and exits with a nonzero code, and must be
treated as BLOCKED/FAIL by the calling smoke test, never as success.
"""

import argparse
import base64
import hashlib
import os
import re
import socket
import ssl
import struct
import sys
import time


def ws_frame(payload: bytes, opcode: int = 0x1) -> bytes:
    """Build one client->server (masked, per RFC 6455) WebSocket frame."""
    b0 = 0x80 | opcode  # FIN=1
    length = len(payload)
    mask_key = os.urandom(4)
    if length <= 125:
        header = bytes([b0, 0x80 | length])
    elif length <= 0xFFFF:
        header = bytes([b0, 0x80 | 126]) + struct.pack(">H", length)
    else:
        header = bytes([b0, 0x80 | 127]) + struct.pack(">Q", length)
    masked = bytes(c ^ mask_key[i % 4] for i, c in enumerate(payload))
    return header + mask_key + masked


class Buffered:
    """Thin recv() buffer shared by the HTTP-upgrade phase and the
    binary WebSocket-framing phase that follows on the same socket."""

    def __init__(self, sock):
        self.sock = sock
        self.buf = b""

    def _recv_more(self):
        chunk = self.sock.recv(4096)
        if not chunk:
            raise ConnectionError("connection closed by server")
        self.buf += chunk

    def read_until(self, sep: bytes) -> bytes:
        while sep not in self.buf:
            self._recv_more()
        idx = self.buf.index(sep) + len(sep)
        data, self.buf = self.buf[:idx], self.buf[idx:]
        return data

    def read_exact(self, n: int) -> bytes:
        while len(self.buf) < n:
            self._recv_more()
        data, self.buf = self.buf[:n], self.buf[n:]
        return data


def read_ws_frame(buf: Buffered) -> bytes:
    hdr = buf.read_exact(2)
    b1 = hdr[1]
    masked = (b1 & 0x80) != 0
    length = b1 & 0x7F
    if length == 126:
        length = struct.unpack(">H", buf.read_exact(2))[0]
    elif length == 127:
        length = struct.unpack(">Q", buf.read_exact(8))[0]
    mask_key = buf.read_exact(4) if masked else None
    payload = buf.read_exact(length)
    if masked:
        payload = bytes(c ^ mask_key[i % 4] for i, c in enumerate(payload))
    return payload


def do_handshake(host: str, port: int, path: str, subprotocol: str, timeout: float):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE  # test-only fixture cert -- see module docstring
    raw = socket.create_connection((host, port), timeout=timeout)
    tls = ctx.wrap_socket(raw, server_hostname=host)
    key = base64.b64encode(os.urandom(16)).decode()
    req = (
        f"GET {path} HTTP/1.1\r\n"
        f"Host: {host}:{port}\r\n"
        f"Upgrade: websocket\r\n"
        f"Connection: Upgrade\r\n"
        f"Sec-WebSocket-Key: {key}\r\n"
        f"Sec-WebSocket-Version: 13\r\n"
        f"Sec-WebSocket-Protocol: {subprotocol}\r\n"
        f"\r\n"
    )
    tls.sendall(req.encode())
    buf = Buffered(tls)
    resp = buf.read_until(b"\r\n\r\n").decode(errors="replace")
    status_line = resp.split("\r\n")[0]
    ok = (
        " 101 " in status_line
        and re.search(r"^Sec-WebSocket-Protocol:\s*" + re.escape(subprotocol) + r"\s*$", resp, re.IGNORECASE | re.MULTILINE) is not None
    )
    return tls, buf, resp, ok, tls.version(), tls.cipher()


def build_register(domain, ext, contact_host, branch, fromtag, callid, cseq, extra_headers=""):
    return (
        f"REGISTER sip:{domain} SIP/2.0\r\n"
        f"Via: SIP/2.0/WSS {branch};rport\r\n"
        f"Max-Forwards: 70\r\n"
        f"From: <sip:{ext}@{domain}>;tag={fromtag}\r\n"
        f"To: <sip:{ext}@{domain}>\r\n"
        f"Call-ID: {callid}\r\n"
        f"CSeq: {cseq} REGISTER\r\n"
        f"Contact: <sip:{ext}@{contact_host};transport=ws>\r\n"
        f"Expires: 60\r\n"
        f"User-Agent: senma-wss-test-client\r\n"
        f"{extra_headers}"
        f"Content-Length: 0\r\n\r\n"
    )


def recv_sip_response(tls, buf):
    while True:
        payload = read_ws_frame(buf)
        text = payload.decode(errors="replace")
        status_line = text.split("\r\n")[0]
        print("SIP RESPONSE:", status_line)
        code = int(status_line.split(" ")[1])
        if code >= 200 or code in (401, 407):
            return code, text


def do_register(tls, buf, domain, ext, secret):
    callid = os.urandom(8).hex()
    fromtag = os.urandom(4).hex()
    branch = "z9hG4bK" + os.urandom(4).hex()

    msg1 = build_register(domain, ext, "senma-wss-test", branch, fromtag, callid, 1)
    print("--- sending REGISTER #1 (unauthenticated) ---")
    tls.sendall(ws_frame(msg1.encode()))
    code, text = recv_sip_response(tls, buf)

    if code not in (401, 407):
        return code, text

    hdr_name = "WWW-Authenticate" if code == 401 else "Proxy-Authenticate"
    m = re.search(hdr_name + r":\s*Digest\s*(.+)", text, re.IGNORECASE)
    if not m:
        print(f"FAILED: {code} response carried no {hdr_name} header")
        return code, text
    params = dict(re.findall(r'(\w+)="?([^",\r\n]+)"?', m.group(1)))
    realm = params.get("realm", "")
    nonce = params.get("nonce", "")

    ha1 = hashlib.md5(f"{ext}:{realm}:{secret}".encode()).hexdigest()
    ha2 = hashlib.md5(f"REGISTER:sip:{domain}".encode()).hexdigest()
    response = hashlib.md5(f"{ha1}:{nonce}:{ha2}".encode()).hexdigest()
    auth_header_name = "Authorization" if code == 401 else "Proxy-Authorization"
    extra = (
        f'{auth_header_name}: Digest username="{ext}", realm="{realm}", '
        f'nonce="{nonce}", uri="sip:{domain}", response="{response}", algorithm=MD5\r\n'
    )
    msg2 = build_register(domain, ext, "senma-wss-test", branch, fromtag, callid, 2, extra)
    print("--- sending REGISTER #2 (authenticated) ---")
    tls.sendall(ws_frame(msg2.encode()))
    return recv_sip_response(tls, buf)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="asterisk")
    parser.add_argument("--port", type=int, default=8089)
    parser.add_argument("--path", default="/ws")
    parser.add_argument("--mode", choices=["handshake", "register"], default="handshake")
    parser.add_argument("--ext")
    parser.add_argument("--secret")
    parser.add_argument("--domain", help="defaults to --host")
    parser.add_argument("--hold-seconds", type=float, default=0.0,
                         help="keep the WS connection open this long after a successful REGISTER, so the caller can observe the live contact via 'pjsip show contacts'")
    parser.add_argument("--timeout", type=float, default=5.0)
    args = parser.parse_args()
    domain = args.domain or args.host

    tls, buf, resp, ok, tls_version, tls_cipher = do_handshake(
        args.host, args.port, args.path, "sip", args.timeout
    )
    print(f"TLS_OK {tls_version} {tls_cipher}")
    print("UPGRADE RESPONSE:")
    print(resp)

    if not ok:
        print("FAILED: WebSocket upgrade did not return 101 with a matching Sec-WebSocket-Protocol")
        sys.exit(1)
    print("HANDSHAKE_OK")

    if args.mode == "handshake":
        sys.exit(0)

    if not args.ext or not args.secret:
        print("FAILED: --mode register requires --ext and --secret")
        sys.exit(2)

    code, text = do_register(tls, buf, domain, args.ext, args.secret)
    if code == 200:
        print("REGISTER_OK")
        if args.hold_seconds > 0:
            time.sleep(args.hold_seconds)
        sys.exit(0)

    print(f"FAILED: final SIP status was {code}, expected 200")
    print(text)
    sys.exit(1)


if __name__ == "__main__":
    main()
