<?php

/**
 *  This file is part of SNEP.
 *
 *  SNEP is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation, either version 3 of
 *  the License, or (at your option) any later version.
 *
 *  SNEP is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with SNEP.  If not, see <http://www.gnu.org/licenses/lgpl.txt>.
 */

/**
 * Generates SENMA-managed native PJSIP trunk configuration (TASK-0015).
 *
 * A dedicated sibling of Snep_PjsipConf, not a branch added to it and not
 * a merge of the two -- per docs/tasks/0014-pjsip-trunk-provisioning-architecture.md
 * §9: a trunk's object-identity source (trunks.id, an internal,
 * never-shown primary key) and object count (endpoint+auth+aor, plus a
 * conditional registration -- a concept extensions never have at all)
 * are structurally different from an extension's (peers.name, always
 * exactly three objects). Forcing trunk generation through
 * Snep_PjsipConf (built and proven for the simpler, fixed-shape
 * extension case) would repeat the exact anti-pattern TASK-0010 already
 * found and avoided in Snep_InterfaceConf.
 *
 * Scope of this first implementation (TASK-0015, outbound only): the
 * single evidence-backed "REGISTER-based provider" model --
 * technology=pjsip, dialmethod=normal, reverse_auth=true. Inbound
 * identification (an `identify` object, needed only for a NOAUTH/
 * IP-matched PJSIP trunk) is explicitly deferred to TASK-0016 -- see
 * docs/tasks/0014-pjsip-trunk-provisioning-architecture.md §7/§20. No
 * `identify` object is generated by this class.
 *
 * @category  Snep
 * @package   Snep
 */
class Snep_PjsipTrunkConf {

    const AUTH_SUFFIX = '-auth';
    const REGISTRATION_SUFFIX = '-registration';

    /**
     * Same chan_sip-era dtmfmode naming -> PJSIP dtmf_mode rename
     * Snep_PjsipConf already uses for extensions (identical DB values,
     * identical PJSIP target -- no trunk-specific difference found).
     */
    private static $dtmfModeMap = array(
        'rfc2833' => 'rfc4733',
        'inband'  => 'inband',
        'info'    => 'info',
    );

    /**
     * loadConfFromDb - regenerate the SENMA-managed PJSIP trunk config
     * from the current trunks/peers tables and reload res_pjsip.
     *
     * Same full-stateless-rewrite property as Snep_PjsipConf/
     * Snep_InterfaceConf: every call reflects exactly the current DB
     * state, so create/edit/delete/enable all "just work" with no
     * incremental diff/cleanup logic.
     *
     * @throws PBX_Exception_IO if the target file isn't writable, or if
     *         Asterisk reports the PJSIP reload did not succeed.
     */
    public static function loadConfFromDb() {
        $view = new Zend_View();
        $db = Snep_Db::getInstance();

        $config = Zend_Registry::get('config');
        $asteriskDirectory = $config->system->path->asterisk->conf;

        $trunkFileConf = "$asteriskDirectory/snep/senma-pjsip-trunks.conf";

        if (!is_writable($trunkFileConf)) {
            throw new PBX_Exception_IO($view->translate("Failed to open file %s with write permission.", $trunkFileConf));
        }

        $todayDate = date("d/m/Y H:i:s");
        $header  = ";------------------------------------------------------------------------------------\n";
        $header .= "; File: senma-pjsip-trunks.conf - SENMA-generated PJSIP trunk provisioning\n";
        $header .= ";\n";
        $header .= "; Generated: $todayDate\n";
        $header .= "; Copyright(c) 2008-" . date("Y") . " Opens Tecnologia\n";
        $header .= ";------------------------------------------------------------------------------------\n";
        $header .= "; GENERATED FILE -- do not edit manually. Rewritten in full on every trunk\n";
        $header .= "; create/edit/delete/enable (Snep_PjsipTrunkConf::loadConfFromDb()). Manual\n";
        $header .= "; edits are lost on the next write. See\n";
        $header .= "; docs/tasks/0015-pjsip-trunk-provisioning.md.\n";
        $header .= ";------------------------------------------------------------------------------------\n";

        // Only PJSIP trunks -- SIP/IAX2/KHOMP/VIRTUAL/SNEPSIP/SNEPIAX2
        // rows are invisible to this query (canal doesn't start with
        // "PJSIP/"), exactly as PJSIP rows are already invisible to
        // Snep_InterfaceConf's own filters, and as PJSIP extension rows
        // are invisible to this same peer_type='T' filter (Snep_PjsipConf
        // reads peer_type='R' only). No coexistence flag needed (TASK-0014
        // §14, mirroring TASK-0010 §11's identical finding for extensions).
        $sql = "SELECT * FROM peers WHERE peer_type = 'T' AND disabled != true AND canal LIKE 'PJSIP/%'";
        $peer_data = $db->query($sql)->fetchAll();

        $sections = "\n";

        foreach ($peer_data as $peer) {
            // The peers row alone doesn't carry the trunk's own id
            // (needed for object naming, TASK-0014 §10) or its
            // trunk-specific fields (reverse_auth, dialmethod) --
            // joined by name, the same pattern Snep_InterfaceConf's own
            // trunk branch already uses.
            $trunkSelect = $db->select()->from('trunks')->where('name = ?', $peer['name'])->limit(1);
            $trunk = $db->query($trunkSelect)->fetch();
            if (!$trunk) {
                // A peers row with no matching trunks row is not a
                // reachable state through the real UI (both are written
                // in the same transaction, TASK-0015A) -- skip
                // defensively rather than emit a section with no real
                // trunk behind it.
                continue;
            }
            $sections .= self::renderTrunk($peer, $trunk);
        }

        $content = $header . $sections;
        file_put_contents($trunkFileConf, $content);

        self::reload($view);
    }

    /**
     * renderTrunk - build the [trunk-<id>]/[trunk-<id>-auth]/[trunk-<id>]
     * (aor)/[trunk-<id>-registration] sections for one trunk.
     *
     * Object naming per TASK-0014 §10: trunk-<trunks.id>, not
     * trunk-<trunks.name> (a same-shaped but independently-computed
     * string, weaker uniqueness guarantee than the real primary key) and
     * not a bare number (extensions' own bare-peers.name convention is
     * safe only because peers.name IS the dial-plan-relevant identity
     * for extensions; a trunk is never dialed by its own name, so the
     * "trunk-" namespace prefix is free and guarantees no collision with
     * any extension endpoint).
     *
     * @param array $peer  one row from `peers` (peer_type='T')
     * @param array $trunk the matching row from `trunks`
     * @return string
     */
    private static function renderTrunk(array $peer, array $trunk) {
        $id = $trunk['id'];
        $name = "trunk-$id";
        $auth = $name . self::AUTH_SUFFIX;

        // Codecs/NAT: identical transformation to Snep_PjsipConf's
        // extension handling (TASK-0014 §13 confirmed no trunk-specific
        // difference).
        $codecList = array_filter(explode(";", (string) $peer['allow']));
        $allow = implode(",", $codecList);

        $natTokens = array_filter(explode(",", (string) $peer['nat']));
        $forceRport = in_array('force_rport', $natTokens, true) ? 'yes' : 'no';
        $rtpSymmetric = in_array('comedia', $natTokens, true) ? 'yes' : 'no';

        $dtmfMode = isset(self::$dtmfModeMap[$peer['dtmfmode']])
            ? self::$dtmfModeMap[$peer['dtmfmode']]
            : 'rfc4733';

        $port = ($peer['port'] !== '' && $peer['port'] !== null) ? $peer['port'] : 5060;
        $host = $peer['host'];

        $out = "[$name]\n";
        $out .= "type=endpoint\n";
        $out .= "context=" . $peer['context'] . "\n";
        $out .= "disallow=all\n";
        $out .= "allow=$allow\n";
        $out .= "dtmf_mode=$dtmfMode\n";
        if ($peer['callerid'] !== '' && $peer['callerid'] !== null) {
            $out .= "callerid=" . $peer['callerid'] . "\n";
        }
        // from_user/from_domain: direct-name-and-semantics rename from
        // the legacy fromuser=/fromdomain= trunk fields (TASK-0014 §3) --
        // a real carrier requirement for identifying which sub-account
        // an INVITE/REGISTER is for.
        if ($peer['fromuser'] !== '' && $peer['fromuser'] !== null) {
            $out .= "from_user=" . $peer['fromuser'] . "\n";
        }
        if ($peer['fromdomain'] !== '' && $peer['fromdomain'] !== null) {
            $out .= "from_domain=" . $peer['fromdomain'] . "\n";
        }
        $out .= "force_rport=$forceRport\n";
        $out .= "rtp_symmetric=$rtpSymmetric\n";
        // Outbound-only milestone (TASK-0015): this endpoint only ever
        // needs to authenticate ITSELF to the provider (REGISTERing and,
        // if challenged, INVITEing) -- outbound_auth=, not auth=.
        // `auth=` (authenticating requests the *provider* sends *us*) is
        // an inbound concern, deliberately not generated here -- see
        // docs/tasks/0014-pjsip-trunk-provisioning-architecture.md §7/§20.
        $out .= "outbound_auth=$auth\n";
        $out .= "aors=$name\n";
        $out .= "\n";

        $out .= "[$auth]\n";
        $out .= "type=auth\n";
        $out .= "auth_type=userpass\n";
        $out .= "username=" . $peer['defaultuser'] . "\n";
        $out .= "password=" . $peer['secret'] . "\n";
        $out .= "\n";

        // AOR name MUST equal the endpoint name (same res_pjsip_registrar
        // constraint TASK-0009/TASK-0010 §6 already proved for
        // extensions -- applies identically here for any future inbound
        // REGISTER matching, and is simply the correct/expected sorcery
        // convention regardless). Static contact=<host>:<port>: this is
        // how Asterisk resolves where to actually send an outbound
        // INVITE placed through this endpoint -- independent of, and not
        // populated by, the separate outbound registration object below
        // (that object only maintains the provider's own liveness/
        // routing state; it does not feed back into this AOR's contact
        // list). Standard practice for a provider trunk with a known,
        // fixed host, register-required or not.
        $out .= "[$name]\n";
        $out .= "type=aor\n";
        $out .= "contact=sip:$host:$port\n";
        $out .= "\n";

        // Registration: only for the model this milestone actually
        // implements (reverse_auth=true, i.e. "make Asterisk register
        // outbound to this provider" -- TASK-0014 §5's precise reading
        // of the legacy reverse_auth field). A trunk with reverse_auth
        // false needs no registration object at all -- the static AOR
        // contact above is already sufficient for outbound-only calling.
        if ($trunk['reverse_auth']) {
            $registration = $name . self::REGISTRATION_SUFFIX;
            $username = $peer['defaultuser'];
            $out .= "[$registration]\n";
            $out .= "type=registration\n";
            $out .= "outbound_auth=$auth\n";
            $out .= "client_uri=sip:$username@$host:$port\n";
            $out .= "server_uri=sip:$host:$port\n";
            $out .= "retry_interval=60\n";
            $out .= "\n";
        }

        return $out;
    }

    /**
     * reload - reload res_pjsip only, surfacing failure instead of
     * silently assuming success. Identical mechanism/reasoning to
     * Snep_PjsipConf::reload() (TASK-0011) -- one PJSIP sorcery config
     * tree, one reload command, reused verbatim rather than
     * reimplemented.
     *
     * @throws PBX_Exception_IO if the reload did not report success.
     */
    private static function reload(Zend_View $view) {
        $asteriskAmi = PBX_Asterisk_AMI::getInstance();
        $result = $asteriskAmi->Command("module reload res_pjsip.so");

        $data = isset($result['data']) ? $result['data'] : '';

        if (stripos($data, 'reloaded successfully') === false) {
            $log = Zend_Registry::get('log');
            $log->err("Snep_PjsipTrunkConf: 'module reload res_pjsip.so' did not report success: " . $data);
            throw new PBX_Exception_IO($view->translate("Failed to reload Asterisk PJSIP configuration: %s", $data));
        }
    }

}
